---
- name: Install UAMS client
  hosts: test-servers
  remote_user: root

  environment:
    UAMS_ACCESS_TOKEN: "{{ uams_access_token }}"
    UAMS_METADATA: "{{ uams_metadata }}"
    SWO_URL: "{{ swo_url }}"

  roles:
    - role: "{{ lookup('env', 'HOME') }}/project/"  # yamllint disable-line rule:role-name
